# Generated by Django 5.2.8 on 2026-01-12 06:38
"""This migration is here to pre-populate the db with initial users."""

from django.db import migrations
from django.contrib.auth.hashers import make_password

users_data = [
    {"username": "mad_max", "call_sign": "Mad Max", "password": "M@d-m@X2042"},
    {"username": "claptrap", "call_sign": "CL4P-TP", "password": "$up3r_$3cr3t"},
]


def create_users(apps, schema_editor):
    Raider = apps.get_model("users", "Raider")
    for user in users_data:
        Raider.objects.create(username=user["username"],
                              call_sign=user["call_sign"],
                              password=make_password(user["password"]))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users)
    ]
