# Generated by Django 5.2.8 on 2026-01-01 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='временная метка'),
            preserve_default=False,
        ),
    ]
