# Generated by Django 5.2.8 on 2026-01-12 07:35
"""This migration is here to pre-populate the db with initial points."""

from django.db import migrations
from django.contrib.gis.db.models.fields import Point as PointField
import json
import os


def get_data_from_datafile(filename: str) -> dict:
    """We need to get to a sibling directory (called 'fixtures') to read data from .json files there."""
    # First, we need to get path to the current file
    path = os.path.realpath(__file__)
    # Then the directory of the current file
    dirpath = os.path.dirname(path)
    # replace for target directory name. We know, we're in 'migrations' and need to get to
    # sibling 'fixtures' directory:
    dirpath = dirpath.replace('migrations', 'fixtures')
    # get the full path to file
    filename = os.path.join(dirpath, filename)

    with open(filename, 'r') as file:
        data = json.load(file)

    return data


def create_initial_points(apps, schema_editor):
    """We've got some points already stored in a json file. We'll also need Raider model from users
    to mark the points."""
    # Get data from .json file
    data = get_data_from_datafile('points.json')

    points = data['points']  # actual data about the points

    # We'll need our models
    Point = apps.get_model("rest_api", "Point")  # getting Point model
    Raider = apps.get_model("users", "Raider")  # getting user model for ForeignKey

    for point in points:
        raider = Raider.objects.get(pk=point.get('user', 1))
        Point.objects.create(
            title=point['title'],
            location=PointField(x=point['location']['latitude'], y=point['location']['longitude']),
            user=raider)


def create_initial_messages(apps, schema_editor):
    """Fill the db with some messages for existing points"""
    # Get data from .json file
    data = get_data_from_datafile('messages.json')

    messages = data['messages']

    # Getting models to operate with
    Message = apps.get_model("rest_api", "Message")
    Point = apps.get_model("rest_api", "Point")  # getting Point model for ForeignKey
    Raider = apps.get_model("users", "Raider")  # getting user model for ForeignKey

    for msg in messages:
        raider = Raider.objects.get(pk=msg.get("user", 1))
        point = Point.objects.get(pk=msg.get("point", 1))
        Message.objects.create(text_content=msg.get("text_content", "text content here"),
                               point=point,
                               user=raider)


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_message_time_create'),
        ('users', '0002_populating')  # we must first populate users
    ]

    operations = [
        migrations.RunPython(create_initial_points),
        migrations.RunPython(create_initial_messages)
    ]
